-- COMO A C (linguagem de programação) API DO RAGNAROK É MUITO LIMITADA, RESOLVI UTILIZAR APENAS O LEVEL DO HOMUNCULUS
-- PARA TENTAR ADIVINHAR AS HABILIDADES E SEU NIVEL, DESSA FORMA CONSIGO SABER O COOLDOWN E A QUANTIDADE DE SP.

-- EU NÃO TENHO ACESSO:
-- O COOLDOWN DAS SKILLS
-- NIVEL DAS SKILLS
-- NÃO TENHO ACESSO A QUAL BASE VOCẼ UTILIZOU PARA CRIAR O HOMUN S
-- LEVEL DO HOMUN OU O LEVEL DO DONO

-- EU TENHO ACESSO:
-- O TIPO DO HOMUNCULU
-- HP E SP
-- O ID DO HOMUNCULU
-- O ID DO DONO
-- O ALCANSE DAS HABILIDADES

-- QUALQUER BUG ABRA UM ISSUE NO REPO E IREI CORRIGIR ASSIM QUE POSSÍVEL.
-- https://github.com/maxmx03/USER_AI/issues/new

MyLevel = 100 -- NIVEL ATUAL DO MEU HOMUNCULUS (ELEANOR)
